imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['MeLikeyWebAppBundle']
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    port:      %mailer_port%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    encryption: %mailer_encryption%
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }

snowcap_mailjet:
    api_key: %mailjet_api_key%
    secret_key: %mailjet_secret_key%
    debug: 0

fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: MeLikey\MusicLoverBundle\Entity\MusicLover
    registration:
        confirmation:
            enabled: true
    from_email:
        address: contact@melikeyradio.com
        sender_name: Me Likey Radio

fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
