parameters:
#    me_likey_music_lover.example.class: MeLikey\MusicLoverBundle\Example

services:
#    me_likey_music_lover.example:
#        class: %me_likey_music_lover.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
