MeLikey\RadioBundle\Entity\PlaylistItem:
    type: entity
    repositoryClass: PlaylistItemRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        position:
            type: integer
    manyToOne:
        playlist:
            targetEntity: Playlist
            inversedBy: playlistItems
        track:
            targetEntity: Track
            joinColumn:
                nullable: false
