MeLikey\RadioBundle\Entity\Tag:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullable: false
            unique: true  
