MeLikey\RadioBundle\Entity\Track:
    type: entity
    repositoryClass: TrackRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        created:
            type: datetime 
        albumart:
            type: string
            nullable: true
        artist:
            type: string
        title:
            type: string
        musiclabel:
            type: string
            nullable: true
        website:
            type: string
            nullable: true
        youtube:
            type: string
            unique: true
            nullable: true
        soundcloud:
            type: string
            unique: true
            nullable: true
        vimeo:
            type: string
            unique: true
            nullable: true
    manyToMany:
        tags:
            targetEntity: Tag 
