parameters:
    melikey_radio.twig_extension.class: MeLikey\RadioBundle\Extension\MeLikeyTwigExtension
    validator.unique.is_unsubscribed_to_newsletter.class: MeLikey\RadioBundle\Validator\Constraints\isUnsubscribedToNewsletterValidator

services:
    melikey_radio.twig.extension:
        class: %melikey_radio.twig_extension.class%
        tags:
            - { name : twig.extension }

    validator.unique.is_unsubscribed_to_newsletter:
        class: %validator.unique.is_unsubscribed_to_newsletter.class%
        arguments: [@snowcap_mailjet.client]
        tags:
            - { name: validator.constraint_validator, alias: is_unsubscribed_to_newsletter_validator }
