parameters:
    twig_js.amd_module_compiler.class: "TwigJs\Compiler\ModuleCompiler\AmdCompiler"

services:
    twig_js.amd_module_compiler:
        class: "%twig_js.amd_module_compiler.class%"
        arguments: [false]
