parameters:
    me_likey_web_app.amd_module_compiler.class: "MeLikey\WebAppBundle\TwigJs\Compiler\AmdModuleCompiler"

services:
    me_likey_web_app.amd_module_compiler:
        class: "%me_likey_web_app.amd_module_compiler.class%"
